# 应用配置
app:
  title: "GoInsight" # 网站Title
  listen_address: "localhost:8083" # 应用监听地址
  environment: "dev" # 环境设置，可选值为dev/prod
  secret_key: "A9$k!pZ3@rT7&xQ1#Lf8^Vm2*Ws6%Hd0" # 必须32位长度，应用密钥，请妥善保管

crontab:
  sync_db_metas: "*/5 * * * *" # 每5分钟同步一次远程数据库库表元数据到本地数据库

# 日志配置
log:
  level: "info" # 日志级别
  root_dir: "./logs" # 日志根目录

# MySQL数据库配置，用于存储应用数据
database:
  driver: "mysql" # 数据库驱动
  host: "127.0.0.1" # 数据库主机
  port: 3306 # 数据库端口
  database: "goinsight" # 数据库名称
  username: "goinsight_rw" # 数据库用户名
  password: "1234.Com!" # 数据库密码
  charset: "utf8mb4" # 数据库字符集
  max_idle_conns: 64 # 最大空闲连接数
  max_open_conns: 64 # 最大打开连接数
  conn_max_life_time: 3600 # 连接的最大存活时间
  conn_max_idle_time: 3600 # 连接的最大空闲时间

# Redis配置，用于缓存应用数据
redis:
  host: "127.0.0.1" # Redis主机
  port: 6379 # Redis端口
  password: "" # Redis密码
  db: 0 

# 数据查询配置
das:
  max_execution_time: 600000 # 查询语句最大查询执行时间
  default_return_rows: 100 # 查询默认返回行数
  max_return_rows: 100 # 查询默认最大返回行数
  allowed_useragents: [
      "Chrome",
      "Firefox",
      "Safari",
      "Trident",
      "Presto",
      "Postman",
    ] # 允许的UA

# GitHub's Online Schema-migration Tool for MySQL
# https://github.com/github/gh-ost
ghost:
  path: "/usr/local/bin/gh-ost" # Gh-ost工具路径
  args: # Gh-ost工具参数列表
    [
      "--allow-on-master",
      "--assume-rbr",
      "--initially-drop-ghost-table",
      "--initially-drop-old-table",
      "-initially-drop-socket-file",
      "-exact-rowcount",
      "--approve-renamed-columns",
      "--concurrent-rowcount=false",
      "--chunk-size=800",
    ]

# 消息通知配置，用于工单消息推送
notify:
  notice_url: "http://localhost:8083/"
  wechat:
    enable: true
    webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=1234"
  dingtalk:
    enable: false
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=1234"
    keywords: "goinsight"
  mail:
    enable: false
    username: "xxx@163.com"
    password: "1234.com"
    host: "smtp.163.com"
    port: 465
